name: Main

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install
        working-directory: "./server"

      - name: Run linting
        run: pnpm lint
        working-directory: "./server"

      - name: Run code style
        run: pnpm style
        working-directory: "./server"

      - name: Run tests
        run: pnpm test:ci
        working-directory: "./server"

      - name: Build
        run: pnpm build
        working-directory: "./server"

      - name: Coveralls
        if: github.repository == 'socraticprogrammer/youtube-downloader'
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
